### ISSUE TITLE
Не корректно отображаются символы в Windows 8

### ISSUE THREAD

**Issue by AlexKorovyansky** [gdgomsk/MyRole#1]
Не корректно отображаются символы на http://myrole.gdgomsk.org

http://i.gyazo.com/bb9e8fd4f2f3ce2a00e89d005e48d586.png
OS Windows 8.1 (English), Google Chrome 43.0.2357.124

в IE 11 еще хуже:
http://i.gyazo.com/7269cac468f86c0802d03ba231d21a11.png

**Comment by jacob-l** [comment]
Была проблема с хостером. Пофикшено. В репозитории лежит версия в правильной кодировке.

**Comment by AlexKorovyansky** [comment]
:+1:
